image: debian/bookworm
sources:
    - https://git.sr.ht:~yulqen/yulqen.org
packages:
    - rsync
    - hugo
environment:
    deploy: lemon@joannalemon.com
secrets:
    - ec3b15b5-3539-4e51-8dc7-f37e8200865b
tasks:
    - build: |
        cd yulqen.org
        hugo
    - deploy: |
        cd yulqen.org
        sshopts="ssh -o StrictHostKeyChecking=no -p 2222"
        rsync  -azr --rsh="$sshopts" public/ $deploy:/var/www/yulqen.org/ --exclude '*.xcf' --exclude Makefile --exclude .git --exclude .htaccess --delete 
        
    
