baseURL = "https://yulqen.org"
title = "Yulqen"
theme = "problematic"
languageCode = "en-gb"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "An intentionally quiet and unassuming (and empty) blog"
  copyright = "Copyright © 2022 Yulqen"
  dark = "off"
  highlight = true
  custom_css = ["css/style.css"]
  mainSections = ['blog', 'about', 'stream', 'reading']

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "blog"
    url = "/blog/"
    weight = 10
    post = '| '

  [[menu.main]]
    identifier = "stream"
    name = "Stream"
    title = "Stream"
    url = "/stream/"
    weight = 20
    post = '| '

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "about"
    url = "/about/"
    weight = 20
    post = '| '

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = 20
    post = '| '

  [[menu.main]]
    identifier = "poems"
    name = "Poems"
    title = "Poems"
    url = "/writing/poems/"
    weight = 20
    post = '| '

  [[menu.main]]
    identifier = "reading"
    name = "Reading"
    title = "Reading"
    url = "/reading/"
    weight = 20
    post = '| '

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 20


[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
